(require 'locate)
(defun fbn/locatify ()
  "Convert a buffer with absolute filenames to match one generated by `locate'. It
comes in handy when restoring files from a crash."
  (interactive
   (progn
     (let ((inhibit-read-only t)
           (num-temp-files 0))
       ;; Remove temporary files
       (goto-char (point-min))
       (while (re-search-forward "^.+#.+#$" nil t)
         (progn
           (replace-match "" nil nil)
           (kill-line)
           (incf num-temp-files)))
       (message "%i temporary files removed" num-temp-files)
       ;; Convert to match locate buffer
       (goto-char (point-min))
       (while (re-search-forward "^\\(.\\)" nil t)
         (replace-match "    \\1" nil nil))
       (goto-char (point-min))
       (insert "  /:
 Matches for *:

"))
     (forward-char 4)
     (locate-mode))))


(provide 'init-locate)
