(require 'swiper)

(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq ivy-count-format "(%d/%d) ")
(setq ivy-height 11)

(global-set-key (kbd "C-M-s") 'swiper)
(define-key isearch-mode-map (kbd "M-i") 'swiper-from-isearch)
(global-set-key (kbd "M-y") 'counsel-yank-pop)
(global-set-key (kbd "C-c C-r") 'ivy-resume)
;(global-set-key (kbd "<f6>") 'ivy-resume)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
;(global-set-key (kbd "<f1> l") 'counsel-load-library)
;(global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
;(global-set-key (kbd "<f2> u") 'counsel-unicode-char)
;(global-set-key (kbd "C-c g") 'counsel-git)
;(global-set-key (kbd "C-c j") 'counsel-git-grep)
;(global-set-key (kbd "C-c k") 'counsel-ag)
;(global-set-key (kbd "C-x l") 'counsel-locate)
;(global-set-key (kbd "C-S-o") 'counsel-rhythmbox)

(setq magit-completing-read-function 'ivy-completing-read)
(setq projectile-completion-system 'ivy)

(require 'org)
(setq counsel-org-goto-display-style 'path)
(setq counsel-org-goto-separator " ➜ ")
(setq counsel-org-goto-face-style 'org)
(setq counsel-org-goto-display-tags nil)
(setq counsel-org-goto-display-todo t)
(define-key org-mode-map (kbd "C-c C-j") 'counsel-org-goto)
(define-key org-mode-map (kbd "C-u C-c C-j") 'counsel-org-goto-all)

(require 'counsel-gtags)
(setq counsel-gtags-ignore-case t)
(setq counsel-gtags-auto-update t)
(setq counsel-gtags-use-input-at-point nil)
(with-eval-after-load 'counsel-gtags
  (define-key counsel-gtags-mode-map (kbd "M-.") 'counsel-gtags-dwim)
  (define-key counsel-gtags-mode-map (kbd "M-]") 'counsel-gtags-find-reference)
  (define-key counsel-gtags-mode-map (kbd "C-M-.") 'counsel-gtags-find-definition)
  (define-key counsel-gtags-mode-map (kbd "C-c M-d") 'counsel-gtags-find-definition)
  (define-key counsel-gtags-mode-map (kbd "C-c M-r") 'counsel-gtags-find-reference)
  (define-key counsel-gtags-mode-map (kbd "C-c M-s") 'counsel-gtags-find-symbol)
  (define-key counsel-gtags-mode-map (kbd "C-c M-f") 'counsel-gtags-find-file)
  (define-key counsel-gtags-mode-map (kbd "C-c M-p") 'counsel-gtags-go-backward)
  (define-key counsel-gtags-mode-map (kbd "C-c M-n") 'counsel-gtags-go-forward)
;  (define-key counsel-gtags-mode-map (kbd "C-c M-?") 'fbn/helm-gtags-show-definition)
)

(provide 'init-ivy)
