(require 'php-eldoc)
(require 'php-mode)
(require 'geben)
(defun fbn/php-hook ()
  (c-set-style "stroustrup")
  (c-set-offset 'case-label' 4)
;  (local-set-key (kbd "RET") 'newline-and-indent)
  (local-unset-key (kbd "C-."))
  (local-set-key (kbd "C-c C-n") 'fbn/php-insert-namespace)
  (php-eldoc-enable)
;  (ggtags-mode)
  (helm-gtags-mode)
  ;; Toggle geben debugger with F6
  (local-set-key (kbd "<f6>") '(lambda () (interactive)
                                 (if dbgp-listeners (call-interactively 'geben-end)
                                   (call-interactively 'geben))))
  (flycheck-mode))
(add-hook 'php-mode-hook 'fbn/php-hook)

;; Add function to insert namespace
(defun fbn/php-insert-namespace ()
  "Add namespace to PHP file"
  (interactive)
  (let ((parts (butlast (cdr (s-split "/" buffer-file-name)))))
    (if (projectile-project-p)
        (setq parts (member (projectile-project-name) parts)))
    (goto-line 3)
    (if (s-equals? (word-at-point) "namespace")
        (kill-line 1)
      (open-line 1))
    (insert "namespace " (s-join "\\" parts) ";")
    (newline)))


(provide 'init-php)
